CREATE DATABASE IF NOT EXISTS relaydb;
USE relaydb;
CREATE USER  IF NOT EXISTS 'kwic'@'%' IDENTIFIED BY 'kwicDB5539!';
GRANT ALL PRIVILEGES ON relaydb.* TO 'kwic'@'%';
FLUSH PRIVILEGES;

/*
DROP TABLE relaydb.TBRL_CDCLS;
DROP TABLE relaydb.TBRL_CDDTL;
DROP TABLE relaydb.TBRL_GRPINF;
DROP TABLE relaydb.TBRL_MBRINF;
DROP TABLE relaydb.TBRL_MBRBNK;
DROP TABLE relaydb.TBRL_PRFNBM;
DROP TABLE relaydb.TBRL_TRSHIS;
DROP TABLE relaydb.TBRL_TRSRQ;
DROP TABLE relaydb.TBRL_INVLD;
DROP TABLE relaydb.TBRL_TRSLOG;
DROP TABLE relaydb.TBRL_SQNC;
*/

CREATE TABLE IF NOT EXISTS relaydb.TBRL_CDCLS (
	CDCLS_CLSCD	VARCHAR(4)	NOT NULL	COMMENT '분류코드'
	,CDCLS_NM	VARCHAR(50)	NOT NULL	COMMENT '분류명'
	,CDCLS_LEN	NUMERIC(4,0)	NOT NULL	COMMENT '상세코드제한크기'
	,CDCLS_YN	CHAR(1)		NOT NULL	DEFAULT 'Y'			COMMENT '사용여부'
	,CDCLS_RUSR	VARCHAR(20)	NOT NULL	DEFAULT 'SYSTEM'		COMMENT '마지막 동기화 시각'
	,CDCLS_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	
	,PRIMARY KEY(CDCLS_CLSCD)
) COMMENT='공통코드분류'
;

INSERT INTO relaydb.TBRL_CDCLS (CDCLS_CLSCD, CDCLS_NM, CDCLS_LEN) VALUES ('0001', '거래구분코드', 2);
INSERT INTO relaydb.TBRL_CDCLS (CDCLS_CLSCD, CDCLS_NM, CDCLS_LEN) VALUES ('0002', '거래지점코드', 5);
INSERT INTO relaydb.TBRL_CDCLS (CDCLS_CLSCD, CDCLS_NM, CDCLS_LEN) VALUES ('0003', '은행코드', 3);
INSERT INTO relaydb.TBRL_CDCLS (CDCLS_CLSCD, CDCLS_NM, CDCLS_LEN) VALUES ('0004', '은행응답코드', 4);

CREATE TABLE IF NOT EXISTS relaydb.TBRL_CDDTL (
	CDCLS_CLSCD	VARCHAR(4)	NOT NULL	COMMENT '분류코드'
	,CDDTL_DTLCD	VARCHAR(50)	NOT NULL	COMMENT '코드'
	,CDDTL_NM	VARCHAR(100)	NOT NULL	COMMENT '코드명'
	,CDDTL_ORD	NUMERIC(4,0)	NOT NULL	COMMENT '정렬순서'
	,CDDTL_USEYN	VARCHAR(1)	NOT NULL	DEFAULT 'Y'		COMMENT '사용여부'
	,CDDTL_RUSR	VARCHAR(20)	NOT NULL	DEFAULT 'SYSTEM'	COMMENT '등록자'
	,CDDTL_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'

	,PRIMARY KEY(CDCLS_CLSCD,CDDTL_DTLCD)
) COMMENT='공통코드상세'
;

/*거래구분코드*/
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '20', '입금', 1);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '30', '출금', 2);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '32', '출금', 3);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '31', '부도지급', 4);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '40', '입금이자', 5);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '41', '출금이자', 6);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '51', '입금취소', 7);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '52', '출금취소', 8);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '53', '부도입금취소', 9);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '54', '부도지급취소', 10);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '21', '수탁만기입금', 11);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0001', '60', '수탁만기입금', 12);

/*거래지점코드*/
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00401', 'KB창구입금', 1);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00402', 'KB인터넷뱅킹', 2);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00403', 'KB텔레뱅킹', 3);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00404', 'KB TOPLINE', 4);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00405', 'KB Kiosk', 5);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00406', 'KB Real Time', 6);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00407', '제휴업체(연계기관)', 7);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00408', 'KB Mobile', 8);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00409', '타행CD입금이체', 9);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00410', '당행CD입금이체', 10);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00411', '타행창구입금', 11);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00412', '타행전자망입금', 12);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00413', '자동이체입금', 13);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00414', 'KB ATM현금입금', 14);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00415', '타행ATM현금입금', 15);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01101', '창구단말', 16);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01102', 'CD/ATM', 17);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01103', '인터넷', 18);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01104', 'PC', 19);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01105', '전화', 20);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01106', '타행환', 21);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01107', 'CD공동망', 22);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01108', '전자금융공동망', 23);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01109', '유통정보', 24);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01110', '대량이체', 25);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01111', '한국은행거래', 26);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01112', '대학등록금', 27);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01113', '법원공탁금', 28);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01114', '자동이체', 29);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01115', '실시간이체', 30);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01116', '대학등록금_단말기', 31);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01117', '대학등록금_자동화기기', 32);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '01100', '기타', 33);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '02001', '우리은행 창구', 34);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '02002', '우리은행 텔레뱅킹', 35);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '02003', '우리은행 인터넷', 36);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '02004', '우리은행 자동화기기', 37);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00211', '타행 창구', 38);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00212', '타행 텔레뱅킹', 39);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00213', '타행 인터넷', 40);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00214', '타행 자동화기기', 41);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00215', '타행 기타', 42);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00216', '타행카드 우리은행CD 취급', 43);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00217', '펌뱅킹', 44);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '00202', '기타', 45);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08801', '창구단말', 46);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08802', 'CD/ATM', 47);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08803', '인터넷', 48);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08804', 'PC', 49);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08805', '전화', 50);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08806', '타행환', 51);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08807', 'CD공동망', 52);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08808', '전자금융공동망', 53);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0002', '08800', '기타', 54);

/*은행코드*/
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '002', '산업은행', 1);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '003', '기업은행', 2);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '004', '국민은행', 3);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '005', '외환은행', 4);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '007', '수협중앙회', 5);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '011', '농협', 6);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '020', '우리은행', 7);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '023', 'SC은행', 8);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '027', '한국씨티은행', 9);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '031', '대구은행', 10);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '032', '부산은행', 11);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '034', '광주은행', 12);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '035', '제주은행', 13);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '037', '전북은행', 14);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '039', '경남은행', 15);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '045', '새마을금고중앙회', 16);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '048', '신협중앙회', 17);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '060', 'BOA은행', 18);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '071', '우체국', 19);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '081', '하나은행', 20);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '088', '신한은행', 21);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '209', '동양증권', 22);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '230', '미래에셋증권', 23);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '240', '삼성증권', 24);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '247', '우리투자증권', 25);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '267', '대신증권', 26);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0003', '269', '한화투자증권', 27);

/*은행응답코드(FCS 계좌인증)*/
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0000', '정상', 1);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0001', '전문레이아웃오류', 2);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0007', '조회 은행코드 오류', 3);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0009', '금융결제원 타임아웃', 4);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0111', '날짜오류', 5);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0115', 'CMS계좌로 처리불가', 6);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0116', '생년월일 또는 사업자번호 상이', 7);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0122', '조회대상계좌오류', 8);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0123', '거래금액오류(적금계좌 등)', 9);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0124', '타행거래불가,CMS계좌등', 10);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0126', '해지,잡좌 등', 11);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0131', '미등록된업체계좌', 12);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0132', '업체계좌오류', 13);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0145', '조회대상은행장애', 14);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0146', '금융결제원장애', 15);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0147', '금융결제원 업무시간 아님', 16);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0198', '사업자번호 인증 불가 은행 조회', 17);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', '0199', '기타오류', 18);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A002', '성명,생년월일 불일치', 19);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A004', '성명조회실패', 20);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A003', '인증기관 자료없음', 21);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A005', '생년월일오류', 22);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A009', '생년월일 미 세팅', 23);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A032', '인증기관 장애', 24);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A034', '인증기관과 통신장애', 25);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A050', '사용자가 인증기관에 정보도용차단 요청상태', 26);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A098', 'KSNET 내부 서버 간 타임아웃', 27);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0004', 'A099', 'KSNET 내부기타 오류', 28);

/*국민은행 응답코드(원화)*/
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0000', '정상처리', 1);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0001', '전문형식불일치', 2);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0002', '전문구분코드 및 업무구분코드 오류', 3);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0003', '업무장애SET', 4);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0005', '은행시스템장애(DB CALL오류)', 5);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0006', '업체기관코드 오류(해당업체코드 없음)', 6);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0007', '은행코드오류', 7);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0009', '은행시스템장애(DB CALL오류)', 8);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0100', '전문번호 없음', 9);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0101', '전문번호 중복', 10);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0102', '이체 업무 미개시', 11);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0103', '이체 업무 마감', 12);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0105', '이체계좌점 마감', 13);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0106', '입금계좌가 법착계좌이거나 대손상각계좌임', 14);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0107', '전문번호 중복', 15);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0111', '이체일자 오류', 16);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0112', '이체금액 오류(금액이 숫자가 아닌경우 포함), 이체한도초과', 17);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0116', '주민번호 또는 사업자번호 상이', 18);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0117', '입금계좌가 해지/거래중지좌임', 19);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0119', '출금계좌 비밀번호3회이상 오류', 20);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0120', '계좌 자릿수 오류', 21);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0122', '입금계좌오류(계좌CHECK DIGIT오류)', 22);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0123', '입금한도오류', 23);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0128', '실명 미확인 계좌', 24);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0129', '해지계좌', 25);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0130', '거래중지좌편입계좌', 26);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0131', '출금모계좌 미등록', 27);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0132', '입출금계좌 오류', 28);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0133', '출금계좌 잔액부족', 29);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0138', '입금등록계좌가 없음(입출등록 해지요청시)', 30);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0140', '전자금융거래 제한(창구거래만 가능. 다른 계좌를 사용하거나 계좌주가 제한을 해제하면 가능)', 31);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0143', '타행환 은행코드 오류', 32);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0145', '타행환 입금은행 오류', 33);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0148', '타행환 송신중 TIME OVER', 34);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0149', '타행환 입금계좌 오류', 35);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0150', '잔액증명 발급계좌', 36);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0151', '해당 지점 마감', 37);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0152', '전출 해지 계좌', 38);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0153', '점코드 오류', 39);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0154', '입금적요(의뢰인명) 오류', 40);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0155', 'CMS계좌 마감후 입출금 불가', 41);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0156', '마감후 처리 불가', 42);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0157', '입출금계좌 오류(외화계좌)', 43);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0158', '사망또는 실종신고 계좌임', 44);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0159', '사고신고된 계좌임', 45);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0160', '인감분실신고된 계좌임', 46);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0161', '잔고확인서 또는 납입증명서 발부된 상태임', 47);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0162', '입출 요청계좌가 없음', 48);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0163', '이미해지폐기된 계좌임', 49);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0164', '이미폐기현존 계좌임', 50);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0167', '기등록 된 채권(어음)번호', 51);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '0199', '기타오류(입출관련기타오류, 전문처리기타오류)', 52);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2000', '자동이체 신청구분오류', 53);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2001', '납부자번호 오류', 54);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2002', '대상납부자없슴(자동이체미등록)', 55);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2003', '해지신청시 계좌번호 불일치', 56);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2004', '신규신청불가', 57);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2005', '이중신청(동일납부자번호&동일계좌)', 58);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2007', '자동이체해지되었음(영업점해지)', 59);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2008', '자동이체해지되었음(업체해지)', 60);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2015', '이중신청(동일납부자번호&상이계좌)', 61);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2020', '복기부호 오류', 62);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2023', '입.출금계좌 미등록', 63);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2024', '입금계좌 지점 미확정(입출금등록 등록상태)', 64);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2027', '입출금등록 해지상태임 혹은 동일한 계좌 등록', 65);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2028', '주민번호 및 사업자번호 오류', 66);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2030', '출금이체시 이체비밀번호 오류', 67);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '2036', '계좌이동제를 통한 출금은행 변경해지', 68);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '5413', '기타오류', 69);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '5802', '금액상이 (가상계좌로 이체시)', 70);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7101', '수취인계좌 없음', 71);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7102', '수취인계좌 오류', 72);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7103', '수취인계좌번호내의 점번호 틀림', 73);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7104', '수취인계좌 잔액증명서 발급', 74);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7105', '수취인계좌 통장정리 후 거래가능', 75);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7106', '수취인계좌 입금한도 초과', 76);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7107', '주민등록번호 불일치', 77);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7108', '총금액 상위', 78);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7142', '개설은행 개시이전 상태                           ', 79);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7201', '통장분실 재발행계좌', 80);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7202', '법적제한계좌', 81);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7203', '가명계좌', 82);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7204', '해약계좌', 83);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7205', '잡좌', 84);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7300', '실명 미확인', 85);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7400', '기타 수취불가', 86);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7401', '수취인 계좌 없음', 87);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7402', '수취인 계좌 잔액증명서', 88);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7403', '수취인 계좌 통장정리후 거래가능', 89);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7404', '수취인 계좌 입금한도초과', 90);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7405', '수취인 성명 오류', 91);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7406', '이체 한도 초과', 92);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7407', '총금액 상위', 93);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7408', '통장분실 재발행 계좌', 94);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7409', '법적제한 계좌', 95);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7410', '이관(전출)계좌', 96);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7411', '해약 계좌', 97);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7412', '잡좌', 98);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7413', '기타수취불가(해당 입금계좌점 연락)', 99);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7414', '추심대전 수수료상위', 100);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7415', '불입금 상위(1회 불입단위가 있는 경우)', 101);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7416', '불입횟수 초과(해당 입금계좌점 연락)', 102);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7417', '타행이체거래 불가 계좌', 103);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7418', '비실명 계좌', 104);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7419', 'CMS번호 기재 요망', 105);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7420', 'CMS번호 상위', 106);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7430', '개설은행 이체처리중', 107);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7724', '거래중지계좌', 108);
INSERT INTO relaydb.TBRL_CDDTL (CDCLS_CLSCD, CDDTL_DTLCD, CDDTL_NM, CDDTL_ORD) VALUES ('0005', '7XXX', '타행입금관련 전금법오류', 109);



CREATE TABLE IF NOT EXISTS relaydb.TBRL_GRPINF (
	GRPINF_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '단지 일련번호'
	,GRPINF_CNO	VARCHAR(13)	NOT NULL	COMMENT '단지사업자번호'
	,GRPINF_CNM	VARCHAR(100)	NOT NULL	COMMENT '단지사업자명'
	,GRPINF_YN	CHAR(1)		NOT NULL	DEFAULT 'Y'			COMMENT '사용여부'
	,GRPINF_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	,GRPINF_UDT	TIMESTAMP	COMMENT '수정일시'
	
	,PRIMARY KEY(GRPINF_SEQ,GRPINF_CNO)
) COMMENT='단지 정보'
;

/*
INSERT INTO relaydb.TBRL_GRPINF (GRPINF_SEQ, GRPINF_CNO, GRPINF_CNM) VALUES (1, '6938701893', '도이치오토월드');
*/

CREATE TABLE IF NOT EXISTS relaydb.TBRL_MBRINF (
	MBRINF_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '상사 일련번호'
	,GRPINF_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '단지 일련번호'
	,MBRINF_CNO	VARCHAR(13)	NOT NULL	COMMENT '상사사업자번호'
	,MBRINF_CNM	VARCHAR(100)	NOT NULL	COMMENT '상사사업자명'
	,MBRINF_YN	CHAR(1)		NOT NULL	DEFAULT 'Y'	COMMENT '사용여부'
	,MBRINF_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	,MBRINF_UDT	TIMESTAMP	COMMENT '수정일시'
	
	,PRIMARY KEY(MBRINF_SEQ,GRPINF_SEQ,MBRINF_CNO)
) COMMENT='상사 정보'
;

CREATE TABLE IF NOT EXISTS relaydb.TBRL_MBRBNK (
	MBRBNK_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '상사은행 일련번호'
	,MBRINF_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '상사 일련번호'
	,MBRBNK_BNKCD	VARCHAR(3)	NOT NULL	COMMENT '은행코드'
	,MBRBNK_DISCD	VARCHAR(9)	NOT NULL	COMMENT '식별코드'
	,MBRBNK_FBSCD	VARCHAR(8)	NOT NULL	COMMENT '업체코드'
	,MBRBNK_CHNL	VARCHAR(30)	NOT NULL	DEFAULT 'KSNET'	COMMENT '전용선 코드'
	,MBRBNK_RCYN	VARCHAR(1)	NOT NULL	DEFAULT 'N'	COMMENT '복기부호사용여부'
	,MBRBNK_OPDT	VARCHAR(8)	NOT NULL	DEFAULT '00000000'	COMMENT '개시일자'
	,MBRBNK_OPYN	CHAR(1)		NOT NULL	DEFAULT 'N'	COMMENT '개시여부'
	,MBRBNK_YN	CHAR(1)		NOT NULL	DEFAULT 'Y'	COMMENT '사용여부'
	,MBRBNK_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	,MBRBNK_UDT	TIMESTAMP	COMMENT '수정일시'

	
	,PRIMARY KEY(MBRBNK_SEQ,MBRINF_SEQ)
) COMMENT='상사별 은행정보'
;

CREATE TABLE IF NOT EXISTS relaydb.TBRL_PRFNBM (
	PRFNBM_SEQ	INT	UNSIGNED	NOT NULL AUTO_INCREMENT	COMMENT '전문번호관리 일련번호'
	,MBRBNK_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '상사은행 일련번호'
	,PRFNBM_SDAT	VARCHAR(8)	COMMENT '전송일자'
	,PRFNBM_PRFNO	VARCHAR(6)	COMMENT '전문번호'
	,PRFNBM_YN	CHAR(1)		NOT NULL	DEFAULT 'Y'			COMMENT '사용여부'
	,PRFNBM_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	,PRFNBM_UDT	TIMESTAMP	COMMENT '수정일시'
	
	,PRIMARY KEY(PRFNBM_SEQ,MBRBNK_SEQ)
) COMMENT='전문번호관리'
;

CREATE TABLE IF NOT EXISTS relaydb.TBRL_TRSHIS (
	TRSHIS_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '거래내역 일련번호'
	,MBRBNK_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '상사은행 일련번호'
	,TRSHIS_SNDCNT	VARCHAR(1)	NOT NULL	COMMENT '송신횟수'
	,TRSHIS_TRSNO	VARCHAR(6)	NOT NULL	COMMENT '전문번호'
	,TRSHIS_SNDDT	VARCHAR(8)	NOT NULL	COMMENT '전송일자'
	,TRSHIS_SNDTM	VARCHAR(6)	NOT NULL	COMMENT '전송시간'
	,TRSHIS_RSCD	VARCHAR(4)	COMMENT '응답코드'
	,TRSHIS_BRSCD	VARCHAR(4)	COMMENT '은행응답코드'
	,TRSHIS_SCHDT	VARCHAR(8)	COMMENT '조회일자'
	,TRSHIS_SCHNO	VARCHAR(6)	COMMENT '조회번호'
	,TRSHIS_ACCNO	TEXT		NOT NULL	COMMENT '계좌번호'
	,TRSHIS_ASMCNT	VARCHAR(2)	NOT NULL	COMMENT '조립건수'
	,TRSHIS_TRSKN	VARCHAR(2)	NOT NULL	COMMENT '거래구분코드'
	,TRSHIS_TRSAMT	VARCHAR(13)	NOT NULL	COMMENT '거래금액'
	,TRSHIS_ACCAMT	VARCHAR(13)	NOT NULL	COMMENT '계좌잔액'
	,TRSHIS_NTC	VARCHAR(14)	NOT NULL	COMMENT '적요'
	,TRSHIS_CHKNO	VARCHAR(10)	COMMENT '수표번호'
	,TRSHIS_CASH	VARCHAR(13)	NOT NULL	COMMENT '현금'
	,TRSHIS_CHKAMT	VARCHAR(13)	COMMENT '타행수표금액'
	,TRSHIS_ETCAMT	VARCHAR(13)	COMMENT '가계수표,기타금액'
	,TRSHIS_VACCNO	VARCHAR(16)	COMMENT '가상계좌번호'
	,TRSHIS_TRSDT	VARCHAR(8)	NOT NULL	COMMENT '거래일자'
	,TRSHIS_TRSTM	VARCHAR(6)	NOT NULL	COMMENT '거래시간'
	,TRSHIS_BKTRNO	VARCHAR(6)	COMMENT '통장거래 일련번호'
	,TRSHIS_TRBKCD	VARCHAR(3)	NOT NULL	COMMENT '거래은행코드'
	,TRSHIS_BRNCD	VARCHAR(7)	NOT NULL	COMMENT '입금지점코드'
	,TRSHIS_ORGRQ	TEXT		COMMENT '거래내역통지 요청 원본데이터'
	,TRSHIS_ORGRS	TEXT		COMMENT '거래내역통지 응답 원본데이터'
	,TRSHIS_INVLDYN	CHAR(1)		DEFAULT 'N'	COMMENT '결번 요청 여부'
	,TRSHIS_INLRQ	TEXT		COMMENT '결번 요청 원본데이터'
	,TRSHIS_INLRS	TEXT		COMMENT '결번 응답 원본데이터'
	,TRSHIS_INLRQTM	TIMESTAMP	COMMENT '결번 요청 시각'
	,TRSHIS_INLRSTM	TIMESTAMP	COMMENT '결번 응답 시각'
	,TRSHIS_SCHYN	CHAR(1)		NOT NULL	DEFAULT 'N'	COMMENT '업체 조회여부'
	,TRSHIS_SCHDTM	TIMESTAMP	COMMENT '업체 조회일시'
	,TRSHIS_ISUNO	VARCHAR(20)	COMMENT '업체 조회 거래고유번호'
	,TRSHIS_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	,TRSHIS_UDT	TIMESTAMP	COMMENT '수정일시'
	
	,PRIMARY KEY(TRSHIS_SEQ,MBRBNK_SEQ)
) COMMENT='거래내역정보(통지)'
;

CREATE TABLE IF NOT EXISTS relaydb.TBRL_TRSRQ (
	TRSRQ_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '이체요청 일련번호'
	,MBRINF_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '상사 일련번호'
	,TRSRQ_MSGCD	VARCHAR(4)	NOT NULL	COMMENT '메시지코드'
	,TRSRQ_SVRCD	VARCHAR(3)	NOT NULL	COMMENT '업무구분코드'
	,TRSRQ_ISUNO	VARCHAR(20)	NOT NULL	COMMENT '거래고유번호'
	,TRSRQ_PRFNO	VARCHAR(6)	NOT NULL	COMMENT '전문번호'
	,TRSRQ_RCCD	VARCHAR(6)	NOT NULL	COMMENT '복기부호'
	,TRSRQ_OBKCD	VARCHAR(3)	NOT NULL	COMMENT '출금 은행코드'
	,TRSRQ_OACNO	TEXT		NOT NULL	COMMENT '출금 계좌번호'
	,TRSRQ_OPW	TEXT		NOT NULL	COMMENT '출금 계좌비밀번호'
	,TRSRQ_OAMT	VARCHAR(13)	NOT NULL	COMMENT '출금 금액'
	,TRSRQ_ODSC	VARCHAR(20)	COMMENT '출금 계좌적요'
	,TRSRQ_IBKCD	VARCHAR(3)	NOT NULL	COMMENT '입금 은행코드'
	,TRSRQ_IACNO	TEXT		NOT NULL	COMMENT '입금 계좌번호'
	,TRSRQ_IDSC	VARCHAR(20)	NOT NULL	COMMENT '입금 계좌적요'
	,TRSRQ_RQTM	VARCHAR(6)	NOT NULL	COMMENT '이체요청시각'
	,TRSRQ_CMSCD	VARCHAR(16)	COMMENT 'CMS코드'
	,TRSRQ_SRYN	VARCHAR(1)	COMMENT '급여구분'
	,TRSRQ_SIGN	VARCHAR(1)	COMMENT '출금 후 잔액부호'
	,TRSRQ_BLNC	VARCHAR(13)	COMMENT '출금 후 잔액'
	,TRSRQ_FEE	VARCHAR(9)	COMMENT '수수료'
	,TRSRQ_PAYNBR	VARCHAR(15)	COMMENT '처리결과 지급번호'
	,TRSRQ_TRSTM	VARCHAR(6)	COMMENT '처리결과 이체시각'
	,TRSRQ_PRCCD	VARCHAR(4)	COMMENT '처리결과 처리코드'
	,TRSRQ_PYRNBR	VARCHAR(20)	COMMENT '처리결과 납부자번호'
	,TRSRQ_BNKCD	VARCHAR(3)	COMMENT '처리결과 은행코드'
	,TRSRQ_RSYN	CHAR(1)		NOT NULL	DEFAULT 'N'	COMMENT '이체요청 은행 응답여부'
	,TRSRQ_RSCD	VARCHAR(4)	COMMENT '이체요청 은행 응답코드'
	,TRSRQ_RSRSYN	CHAR(1)		NOT NULL	DEFAULT 'N'	COMMENT '결과조회 은행 응답여부'
	,TRSRQ_RSRSCD	VARCHAR(4)	COMMENT '결과조회 은행 응답코드'
	,TRSRQ_TRSRQ	TEXT		NOT NULL	COMMENT '이체요청 원본데이터'
	,TRSRQ_TRSRS	TEXT		COMMENT '이체응답 원본데이터'
	,TRSRQ_RESRQ	TEXT		COMMENT '결과조회요청 원본데이터'
	,TRSRQ_RESRS	TEXT		COMMENT '결과조회응답 원본데이터'
	,TRSRQ_RCVDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '서버 수신 시각'
	,TRSRQ_SNDDT	TIMESTAMP	COMMENT '서버 송신 시각'
	,TRSRQ_RQDT	TIMESTAMP	COMMENT '이체 요청 시각'
	,TRSRQ_RSDT	TIMESTAMP	COMMENT '이체 응답 시각'
	,TRSRQ_RSRCVDT	TIMESTAMP	COMMENT '처리결과 서버 수신 시각'
	,TRSRQ_RSSNDDT	TIMESTAMP	COMMENT '처리결과 서버 송신 시각'
	,TRSRQ_RSRQDT	TIMESTAMP	COMMENT '처리결과 요청 시각'
	,TRSRQ_RSRSDT	TIMESTAMP	COMMENT '처리결과 응답 시각'
	,TRSRQ_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	,TRSRQ_UDT	TIMESTAMP	COMMENT '수정일시'
	
	,PRIMARY KEY(TRSRQ_SEQ,MBRINF_SEQ)
) COMMENT='이체요청정보(송금)'
;

CREATE TABLE IF NOT EXISTS relaydb.TBRL_INVLD (
	INVLD_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '불능통지 일련번호'
	,TRSRQ_SEQ	DECIMAL(15,0)	NOT NULL	COMMENT '이체요청 일련번호'
	,INVLD_CNT	VARCHAR(1)	NOT NULL	COMMENT '송신횟수'
	,INVLD_PRFNO	VARCHAR(6)	NOT NULL	COMMENT '전문번호'
	,INVLD_SNDDT	VARCHAR(8)	NOT NULL	COMMENT '전송일자'
	,INVLD_SNDTM	VARCHAR(6)	NOT NULL	COMMENT '전송시간'
	,INVLD_SCHDT	VARCHAR(8)	COMMENT '조회일자'
	,INVLD_SCHNO	VARCHAR(6)	COMMENT '조회번호'
	,INVLD_OACNO	TEXT		NOT NULL	COMMENT '출금계좌번호'
	,INVLD_IACNO	TEXT		NOT NULL	COMMENT '입금계좌번호'
	,INVLD_OAMT	VARCHAR(13)	NOT NULL	COMMENT '출금금액'
	,INVLD_SUCAMT	VARCHAR(13)	NOT NULL	COMMENT '정상 처리 금액'
	,INVLD_FAILAMT	VARCHAR(13)	NOT NULL	COMMENT '처리 불능 금액'
	,INVLD_DIVCNT	VARCHAR(2)	NOT NULL	COMMENT '분할 처리 건수'
	,INVLD_DIVNO	VARCHAR(2)	NOT NULL	COMMENT '분할 처리 번호'
	,INVLD_DFPRFNO	VARCHAR(6)	NOT NULL	COMMENT '타행 전문 번호'
	,INVLD_ERRAMT	VARCHAR(9)	NOT NULL	COMMENT '불능 통지 금액'
	,INVLD_ERRCD	VARCHAR(3)	NOT NULL	COMMENT '에러 코드'
	,INVLD_IBKCD	VARCHAR(3)	NOT NULL	COMMENT '입금 은행코드'
	,INVLD_ORGRQ	TEXT		COMMENT '불능통지 원본데이터'
	,INVLD_INLYN	CHAR(1)		NOT NULL	DEFAULT 'N'	COMMENT '결번요청 여부'
	,INVLD_INLRQ	TEXT		COMMENT '결번 요청 원본데이터'
	,INVLD_INLRS	TEXT		COMMENT '결번 응답 원본데이터'
	,INVLD_INLRQTM	TIMESTAMP	COMMENT '결번 요청 시각'
	,INVLD_INLRSTM	TIMESTAMP	COMMENT '결번 응답 시각'
	,INVLD_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	,INVLD_UDT	TIMESTAMP	COMMENT '수정일시'
	
	,PRIMARY KEY(INVLD_SEQ,TRSRQ_SEQ)
) COMMENT='이체불능정보(통지)'
;

CREATE TABLE IF NOT EXISTS relaydb.TBRL_TRSLOG (
	LOG_SEQ		INT	UNSIGNED	NOT NULL AUTO_INCREMENT	COMMENT '로그 일련번호'
	,LOG_ISSNO	VARCHAR(20)		COMMENT '거래고유번호'
	,LOG_TIME	VARCHAR(14)	NOT NULL	COMMENT '요청시간'
	,LOG_IP		VARCHAR(15)	NOT NULL	COMMENT '요청 접근IP'
	,LOG_URL	VARCHAR(100)	NOT NULL	COMMENT '요청 URL'
	,LOG_REQ	TEXT		COMMENT '요청 데이터'
	,LOG_RES	TEXT		COMMENT '응답 데이터'
	,LOG_CHNL_REQ	TEXT		COMMENT '채널 요청 데이터'
	,LOG_CHNL_RES	TEXT		COMMENT '채널 응답 데이터'
	,LOG_RDT	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일시'
	
	,PRIMARY KEY(LOG_SEQ)
) COMMENT='거래로그관리'
;

/*######################################### 시퀀스 생성 시작 #########################################*/

CREATE TABLE IF NOT EXISTS relaydb.TBRL_SQNC(
	SQNC_CD		VARCHAR(200)	NOT NULL	COMMENT '시퀀스명'
	,SQNC_SQ	NUMERIC(15)	NOT NULL	COMMENT '시퀀스'
	,SQNC_STVAL	NUMERIC(15)	NOT NULL	COMMENT '시작값'
	,SQNC_MXVAL	NUMERIC(15)	NOT NULL	COMMENT 'MAX값'
	,SQNC_ICVAL	NUMERIC(15)	NOT NULL	DEFAULT 1	COMMENT '증가값'
	,SQNC_CYCLED	VARCHAR(1)	NOT NULL	DEFAULT 'N'	COMMENT '순환여부'

	,CONSTRAINT PK_TBRL_SQNC
		PRIMARY KEY(SQNC_CD)
)
COMMENT='시퀀스정보';

/*#시퀀스생성*/
/*DROP PROCEDURE SP_CREATE_SEQUENCE;*/

delimiter $$
CREATE PROCEDURE IF NOT EXISTS SP_CREATE_SEQUENCE(
	i_cd		VARCHAR(200)
	,i_stval	NUMERIC(15)
	,i_mxval	NUMERIC(15)
	,i_icval	NUMERIC(15)
	,i_cycled	VARCHAR(1)
)
BEGIN
	SET @v_cd	:= i_cd;
	SET @v_stval	:= i_stval;
	SET @v_mxval	:= i_mxval;
	SET @v_icval	:= i_icval;
	SET @v_cycled	:= i_cycled;
	SET @v_exist	:= 0;

	END_TRAN:
	BEGIN
		IF @v_cd='' OR @v_stval>@v_mxval OR @v_icval<1 OR @v_cycled NOT IN ('Y','N') THEN
			LEAVE END_TRAN;
		END IF;
	
		SELECT
			@v_exist := COUNT(SQNC_SQ)
		FROM TBRL_SQNC
		WHERE SQNC_CD = @v_cd;

		IF @v_exist > 0 THEN
			LEAVE END_TRAN;
		END IF;
	
		START TRANSACTION;
			INSERT INTO TBRL_SQNC(
				SQNC_CD
				,SQNC_SQ
				,SQNC_STVAL
				,SQNC_MXVAL
				,SQNC_ICVAL
				,SQNC_CYCLED
			)VALUES(
				@v_cd
				,@v_stval-@v_icval
				,@v_stval
				,@v_mxval
				,@v_icval
				,@v_cycled
			);
		COMMIT;
		LEAVE END_TRAN;
	END;
END $$
delimiter ;


/*#시퀀스삭제*/
/*DROP PROCEDURE SP_DROP_SEQUENCE;*/

delimiter $$
CREATE PROCEDURE IF NOT EXISTS SP_DROP_SEQUENCE(
	i_cd		VARCHAR(200)
)
BEGIN
	SET @v_cd	:= i_cd;

	END_TRAN:
	BEGIN
		IF @v_cd='' THEN
			LEAVE END_TRAN;
		END IF;
	
		START TRANSACTION;
			DELETE FROM TBRL_SQNC
			WHERE SQNC_CD=@v_cd;
		COMMIT;

		LEAVE END_TRAN;
	END;
END $$
delimiter ;

/*#시퀀스증가*/
/*DROP PROCEDURE SP_NEXTVAL;*/

delimiter $$
CREATE PROCEDURE IF NOT EXISTS SP_NEXTVAL(
	IN i_cd		VARCHAR(200)
	,OUT o_sq	NUMERIC(15)
)

BEGIN
	SET @v_cd	:= i_cd;
	SET @v_sq	:= -1;
	SET @o_sq	:= -1;

	START TRANSACTION;
		UPDATE TBRL_SQNC SET
			SQNC_SQ = (CASE WHEN SQNC_MXVAL<SQNC_SQ+SQNC_ICVAL AND SQNC_CYCLED='Y' THEN SQNC_STVAL
					WHEN SQNC_MXVAL<SQNC_SQ+SQNC_ICVAL AND SQNC_CYCLED='N' THEN SQNC_SQ
					ELSE SQNC_SQ+SQNC_ICVAL END)
		WHERE SQNC_CD = @v_cd;
	COMMIT;

	SELECT
		@v_sq := IFNULL(MAX(SQNC_SQ),-1)
	FROM TBRL_SQNC
	WHERE SQNC_CD = @v_cd;

	IF @v_sq<0 THEN
		SET o_sq := NULL;
	ELSE
		SET o_sq := @v_sq;
	END IF;
END $$
delimiter ;

/*#시퀀스조회*/
/*DROP PROCEDURE SP_CURRVAL;*/

delimiter $$
CREATE PROCEDURE IF NOT EXISTS SP_CURRVAL(
	IN i_cd		VARCHAR(200)
	,OUT o_sq		NUMERIC(15)
)

BEGIN
	SET @v_cd	:= i_cd;
	SET @v_sq	:= -1;
	SET @o_sq	:= -1;

	BEGIN
		SELECT
			@v_sq := IFNULL(MAX(SQNC_SQ),-1)
		FROM TBRL_SQNC
		WHERE SQNC_CD = @v_cd;
	END;
	
	IF @v_sq<0 THEN
		SET o_sq := NULL;
	ELSE
		SET o_sq := @v_sq;
	END IF;
END $$
delimiter ;

/*전문번호 채번*/
/*DROP PROCEDURE SP_PFRNBM;*/

delimiter $$
CREATE PROCEDURE IF NOT EXISTS SP_NEXTPFRNO(
	IN mbr_sq	VARCHAR(15)
	,OUT o_sq	NUMERIC(15)
)

BEGIN
	SET @mbr_sq		:= mbr_sq;
	SET @s_dat		:= REPLACE(CURDATE(),'-','');
	
	SET @o_sq		:= -1;
	SET @v_sq		:= 0;

	START TRANSACTION;
		UPDATE TBRL_PRFNBM 
		SET
		PRFNBM_PRFNO = (
			CASE WHEN IFNULL(PRFNBM_SDAT, -1) < @s_dat THEN
				1
			ELSE 
				PRFNBM_PRFNO + 1
			END
		),
		PRFNBM_SDAT = (
			CASE WHEN IFNULL(PRFNBM_SDAT, -1) < @s_dat THEN
				@s_dat
			ELSE 
				PRFNBM_SDAT
			END
		)
		WHERE 1=1
		AND MBRBNK_SEQ = @mbr_sq;
	COMMIT;
	
	SELECT
		@v_sq := IFNULL(PRFNBM_PRFNO, -1)
	FROM TBRL_PRFNBM
	WHERE MBRBNK_SEQ = @mbr_sq
	AND PRFNBM_SDAT = @s_dat;

	IF @v_sq<0 THEN
		SET o_sq := NULL;
	ELSE
		SET o_sq := @v_sq;
	END IF;
	
END $$
delimiter ;


/*KS-NET 개시일자, 개시여부 초기화 이벤트 프로시저*/
/*
delimiter $$
CREATE PROCEDURE IF NOT EXISTS SP_INIT_KSNET(
)
BEGIN
	END_TRAN:
	BEGIN
		START TRANSACTION;
			UPDATE TBRL_MBRBNK SET MBRBNK_OPDT = REPLACE(CURDATE(),'-',''), MBRBNK_OPYN = 'N';
		COMMIT;

		LEAVE END_TRAN;
	END;
END $$
delimiter ;
*/

/*KS-NET 개시일자, 개시여부 초기화 EVENT 생성*/
/*
 * EVENT 사용 시 my.cnf 파일 설정 변경 필요.
 * ==> event_scheduler = ON 추가 후 재시작
 * */
/*
CREATE EVENT IF NOT EXISTS EVENT_INIT_KSNET
ON SCHEDULE 
	EVERY 7 DAY_HOUR /*매일 7시 수행*/
	/*STARTS CURRENT_TIMESTAMP*/ /*EVENT 최초 수행 시간*/
COMMENT 'ks-net initial event'	
DO 
	CALL SP_INIT_KSNET();
*/	

/*######################################### 시퀀스 생성 끝 #########################################*/
CALL SP_CREATE_SEQUENCE('GRPINF_SEQ',2,999999999999999,1,'N')
;
CALL SP_CREATE_SEQUENCE('MBRINF_SEQ',1,999999999999999,1,'N')
;
CALL SP_CREATE_SEQUENCE('MBRBNK_SEQ',1,999999999999999,1,'N')
;
CALL SP_CREATE_SEQUENCE('TRSHIS_SEQ',1,999999999999999,1,'N')
;
CALL SP_CREATE_SEQUENCE('TRSRQ_SEQ',1,999999999999999,1,'N')
;
CALL SP_CREATE_SEQUENCE('INVLD_SEQ',1,999999999999999,1,'N')
;